from collections import deque
n=int(input())
d = deque()
d.append(1)
deque(['3'])
d.append(2)
deque(['2'])
d.append(3)
deque(['3'])
d.appendleft(4)
deque(['4'])
d.pop()
d.popleft()
for i in range(0,len(d)):
    print(d[i],end=' ')
# print(d[0])
'''
deque([1])
d.appendleft(2)
print(d[1],d[0])
deque([2, 1])
d.clear()
deque([])
d.extend('1')

# print(d)
# print(d[0])
# print(d[0],d[1])
deque(['1'])

d.extendleft('234')
deque(['4','3','2','1'])
d.count('1')
d.pop()
deque(['4','3','2'])
d.popleft()
deque(['3','2'])
d.extend('7896')
deque(['3', '2', '7', '8', '9', '6'])
d.remove('2')
deque(['3', '7', '8', '9', '6'])
d.reverse()
deque(['6', '9', '8', '7', '3'])
d.rotate(3)
deque(['8', '7', '3', '6', '9'])
# print(d])
# print(d)
'''

'''s
d.clear()
print(d) 
deque([])
d.extend('1')
print(d) 
deque(['1'])
d.extendleft('234')
print(d) 
deque(['4', '3', '2', '1'])
d.count('1')
1
d.pop()
'1'
print(d)
deque(['4', '3', '2'])
d.popleft()
print(d) 
deque(['3', '2'])
d.extend('7896')
print(d)
deque(['3', '2', '7', '8', '9', '6'])
d.remove('2')
print(d)
deque(['3', '7', '8', '9', '6'])
d.reverse()
print (d)
deque(['6', '9', '8', '7', '3'])
d.rotate(3)
print(d) 
deque(['8', '7', '3', '6', '9'])
'''